// Lightweight fields for the torrent list
export const LIST_FIELDS = [
  'id',
  'name',
  'status',
  'totalSize',
  'percentDone',
  'rateDownload',
  'rateUpload',
  'eta',
  'uploadRatio',
  'addedDate',
  'error',
  'errorString',
  'downloadDir',
  'peersConnected',
  'peersSendingToUs',
  'peersGettingFromUs',
  'seedRatioLimit',
  'seedRatioMode',
  'sizeWhenDone',
  'haveValid',
  'uploadedEver',
  'downloadedEver',
  'trackerStats',
  'activityDate',
  'doneDate',
  'queuePosition',
  'isFinished',
] as const;

// Full fields for the detail view of a single torrent
export const DETAIL_FIELDS = [
  ...LIST_FIELDS,
  'hashString',
  'magnetLink',
  'creator',
  'comment',
  'dateCreated',
  'startDate',
  'pieces',
  'pieceCount',
  'pieceSize',
  'files',
  'fileStats',
  'peers',
  'trackers',
  'trackerStats',
  'wanted',
  'priorities',
  'totalSize',
  'leftUntilDone',
  'desiredAvailable',
  'corruptEver',
  'secondsDownloading',
  'secondsSeeding',
  'bandwidthPriority',
  'downloadLimit',
  'downloadLimited',
  'uploadLimit',
  'uploadLimited',
  'honorsSessionLimits',
  'seedIdleLimit',
  'seedIdleMode',
  'labels',
  'group',
  'percentComplete',
  'metadataPercentComplete',
] as const;
